# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI with Maven and SonarCloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/mingyaracosta/test-dependency-package", "snapshots": { "enabled": "true" } }]'
        servers: '[{ "id": "github", "username": "minyoach@gmail.com", "password": "${{ secrets.GH_PACKAGE_TOKEN }}" }]'
    - name: Build and Run Tests with Maven
      run: mvn -V -B package --file pom.xml
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Analyze with Sonar Cloud
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SC_TOKEN }}
      run: mvn -V -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mingyaracosta_Conway-s-Game-of-Life---Mingyar-Acosta

